# Generated by Django 3.1 on 2020-08-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20200803_1250'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='path',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
